### ISSUE TITLE
transaction not listed in overview

### ISSUE THREAD

**Issue by blockops1** [ZencashOfficial/zencash-swing-wallet-ui#2] opened 2017-07-29 18:37 UTC
When I sent a transaction from a transparent address to someone else's shielded address, I included a memo.
This transaction does not show up in my wallet as a transaction. I have no record of it.

**Comment by vaklinov** [comment] 2017-08-01 19:21
I have reproduced the issue in a test wallet. Sending a transaction T->Z to a Z address not in the current wallet indeed leads to the transaction not being listed. As an example I have the following test wallet:
![gui_transactions](https://user-images.githubusercontent.com/22178263/28842670-3e6b4572-7707-11e7-8919-3c57dcdc402b.png)
That ought to show two outgoing T-Z transactions but does not.

The problem however comes from the underlying ZEN node. The command to list all transactions, does not show them either:

```
./zen-cli listtransactions "" 200 | egrep "address|amount|category"
    "address": "znadrdK2QD23iLyDLUSmnqwVc6iZsVipyLK",
    "category": "receive",
    "amount": 0.00580000,
    "address": "znadrdK2QD23iLyDLUSmnqwVc6iZsVipyLK",
    "category": "receive",
    "amount": 0.00060000,
    "address": "znRF8WTQUyBYHvaLpJPA2kFL9X2f7zfbvcj",
    "category": "send",
    "amount": -0.00630000,
    "address": "znadrdK2QD23iLyDLUSmnqwVc6iZsVipyLK",
    "category": "receive",
    "amount": 0.00100000,
    "address": "zngVsFXXGeSzmys8zkJVzSPTfTVBAkSM7tY",
    "category": "receive",
    "amount": 0.00090000,
    "address": "zngVsFXXGeSzmys8zkJVzSPTfTVBAkSM7tY",
    "category": "send",
    "amount": -0.00090000,
    "address": "znRJ3M3r6BXEiTwfYSP2EQfkAiBQsb9sMjM",
    "category": "receive",
    "amount": 0.00070000,
    "address": "znRJ3M3r6BXEiTwfYSP2EQfkAiBQsb9sMjM",
    "category": "send",
    "amount": -0.00070000,
    "address": "znTY2VFrzsmo5X7CP7regw3TdVzp2LB8hLM",
    "category": "receive",
    "amount": 0.00050000,
    "address": "znTY2VFrzsmo5X7CP7regw3TdVzp2LB8hLM",
    "category": "send",
    "amount": -0.00050000,
```

So the question is: is this a bug in `zend`? Is there a workaround? ... to be investigated.

**Comment by vaklinov** [comment] 2017-08-01 19:35
Interestingly if I send to a Z address in the same wallet, the T->Z transaction gets listed:
```
./zen-cli listtransactions "" 1
[
  {
    "account": "",
    "category": "send",
    "amount": -0.00010000,
    "vout": 1,
    "fee": -0.00010000,
    "confirmations": 0,
    "txid": "cefe12062b1aae112a338ea9770c530ba1a74ec308e635f0b683acc976fe5c3c",
    "walletconflicts": [
    ],
    "time": 1501615562,
    "timereceived": 1501615562,
    "vjoinsplit": [
      {
        "vpub_old": 0.00010000,
        "vpub_new": 0.00000000,
        "anchor": "410e42aa2e6fef993f3dcb93f136cd1546bb0374ba8b2f2cf9397407ce639cdd",
        "nullifiers": [
          "f7dfcf7234ec594b9e72eb93ebe39cda778fb9343a10a657285ab15a48bdf166",
          "bf99e70e09df66a7905466077a867a4b12fdaf059f58a73101f57a9c5c108a44"
        ],
        "commitments": [
          "d92c30ca9be8e59ac38ee528480fcb5c241af1f04b5ff8eaee995f3f90193f64",
          "7e3b37561d14d00cd3613b14abf03bbc94fe1a2f0973285eca8c544ebc383453"
        ],
        "onetimePubKey": "5b60c84d41130b4232e48145f62456bc3bb53afc39526c335900301350da85ef",
        "randomSeed": "a8be61814bdb2349f2627086d8c02fecf1fa18e1e73ecd8a4517aa81cf891a3e",
        "macs": [
          "04a39c8a3688602ba1455a8c2d9e3071d92b370171ff2eeb030aa36ad3b1f0ed",
          "2d1c415c1f409055b2706e0acdebeb5ca30a0bbca4efaecac1adf401b0bcbe99"
        ],
        "proof": "020c5a12b517931e632ad140025be0a244d4a4815745d952f2f34ad030133deaea032c4e2b24a8caf47dc8b2154281d2ce179adbf1ce9653750e39f0f2f07e3554b60a01388104dadc8cc54284b422a11ff20cb4f2da8a3ef39fec3f2967c92482fa7f8cf67aea877ad71a1986f1453486b0d89ae987f96d2d26b20eb581cca5d2f9b3022d054682baedebad765b4788bf9d7422a32bd95e5eb1b6449260a4df85857215021fac8959e3e282d7fcbbee295197d14297e34cec7f6bd03ec48fa07c26bd4036022fcfe5dda66d2cecea00a78c2882841f70b9fa913d87b1f8b4ff72306f8b593303034f646cd5580d7fbdaf82887a87d14eedf72c91def9074b4c75cbafc4831d3f022a603a00b66fd848b1cfe5171bf575c38d4a9f85ff2c67d4d8abc5a01eb604ec",
        "ciphertexts": [
          "89f061027edad168d8f715c6cf990a48de89ffc07c5aee259b7a01ac8cd89d14b7d12e899db59a909bf9e61b75bcf808ce8875e94c418241c9624db58d3ad00b50873e4c4f9291b177df15e14d87e80dfd973ecad7a9a1b90fe21a27ee7151f808d914de1da6dfbbcf98409f98847cdf2dc0ef39994d419814a7e838a5ad0541a6de1f7ffdd12ba747f20ea17876b80bcd53158b77e55d757f8a08464bce9f54d0d5c606db8263ec30a943b66628c03e747ef14c9f9cd90ddb1be28e0de82629b0ff4cf092227285d8d3a5a8a32f67893b90c62dcbacb208ccf5aa6b31fc90df00998ad05bee95121c2cd94aa47fb1d0b062046742a41e18b6706ec1e5eca269c65bea76a132bd3af8bf4af48a70bd1b240e9184f65d81aa0c385a52e358ee66fed410992c29fba79dc8319db97ecebc1f7a1c6fdefe005b4415d2243f46ecd02e8521c87aa4c625b3240a7d6494373b4463e4e6c8426f9a95238f22dcc706ff00b0ae73e7ebf9f8085a628ad70bc86a04ef602ff8f35caccf6dc51f2376232c8dd3b927d37092860f2611c9c9c58708508247b3804c88084da48decea88cfeb81841f5980d24b37369d8c49cb1ae243bc6a7a4c61f5e07776fac9d5a39941664c7491983202aafed206fb57e4cd4a8282ed424189979e7f21dbf5f33d141a58ea317b52c26db71ca4f675db8ef567bd84e767018371d8f94a55576aa97c4eeeec5c3a905aba0de8788b928923d9c959884718ace0e40cbfbc3528963fddfa6d2c103aa1baec7cea7cc27b08513df9f531452a7459b552bdab2d8710042f878d839bd218e0ea1c7ac3686c7699d2690edba96e665d3c47feff",
          "9ce80504df6af90fc5a96702f23ce02b1337967ab4be184a41e809cb849b6b5729ac15b1c30b27240dfd20854d8fbe8803d756d1ab69184acafc970c0cd4b6ccb38111280397d369b3e463c1a0ae38a76531326f0a56564aac53bda30cb94e06ae185408d67c861a8287d8d943e0ab3d41ba1492453283ed25bb85c9b1139343504833995cc6534539eb2f8da5212078b6a9eef58bc2077ed62c399f6e9671dbeb83480fb9c1a259fccc9fb83458b48e6663ada37b9846fd5177374a6f4ae7a626c8e2729443f0e02679d06f701d8529c9e37c9e9552c26d828d17d0a9d0a64c0aa26496219ab53c854161680a3ea6396c89050576b0e95d94ffe1cdc257ea60871c60f6b00149349dd8ea8d9148f7dbe3de1a89e677103dd8764a5965644302f3177a37ee70c52c9dfa647cd191d7d06d13b9a559f72490acb6efb671e77b2cf5093ca7b023beb8821141d95c2834effe58165381c089e1b90623be5eb5c3d05904eb5a356071b1cd0ba0b90c029fbeedc31d026353fce92ee1d74b1764e609532c62abc614dd2234ec751bc15ca7db85f91313312dc8813e7c210902a4e4d98efd22433257a01a015011f2379b556898005c2dbe8772d601c802d0d0b5a5df5cfdcfcd4a8724331b1bae8d746d9079557a4f7281ae3b36f5d8d8c512a7330fa0f90757e2d32e016de7a50e09ba632e17687d0f858453c775a5ea01a6723c76a33d87871ea96d56fc90e9e0a7f176a603a0ad6091afd287c0f575aab0ac1620f01bba4d23572b747cd2a7adee9ace8af53b5c6a73f1d5cec06f6f0acca60b68a6501f19da1de5f8192edd15791b922ad169bc5e407aa59d60"
        ]
      }
    ],
    "size": 2128
  }
]
```
listed as:
![tz2](https://user-images.githubusercontent.com/22178263/28843404-b8d3445c-7709-11e7-95f1-2f53e908699b.png)

**Comment by vaklinov** [comment] 2017-08-01 19:37
I will also test with ZCash and report a bug to them if it is reproducible... later on.

**Comment by macdaddyillness** [comment] 2017-09-16 16:20
i also cannot see any transactions i have been mining on zhash and was paid today but see nothing in my transactions i used the wallet address generated on sign up and nothing has been well over an hour since payment this is version 0.73.1 for windows and i got the link from the voskcoin youtube channel might have to abandon this wallet and take a loss if i cant find a solution thanks for your help and time

**Comment by vaklinov** [comment] 2017-09-17 19:48
@macdaddyillness What you are describing is a completely separate problem (not getting incoming payment from a mining pool). Please use the block explorer:
https://explorer.zensystem.io/
to double check if the payment has arrived or not. If you see it in the block explorer but not in the GUI wallet, maybe I can support you then...

**Comment by macdaddyillness** [comment] 2017-09-17 22:52
Hello and thank you so much for the reply I did get it figured out the wallet itself had synced completely and once it did all transactions are showing properly however I didn't realize that if you exit the program it has to re sync all over again and if your miner is running can take several hours to complete but all is well now and I thank you for your help

**Comment by vaklinov** [comment] 2017-10-03 08:10
Regarding the original problem report:
```
I sent a transaction from a transparent address to someone else's shielded address... This transaction does not show up in my wallet as a transaction. I have no record of it.
```
Comments by the ZCash team:
https://github.com/zcash/zcash/issues/1438#issuecomment-326857454
https://github.com/zcash/zcash/issues/1438#issuecomment-326991345
indicate that this is currently a "feature". It may be modified in the future to keep a record of outgoing T->Z transactions.

**Comment by St3x** [comment] 2019-02-09 13:51
Is this issue still relevant ?

**Comment by Sto1cNate** [comment] 2019-04-25 22:17
@zennermac should be able to close this one.

**Closed** 2019-04-25 23:03 UTC
