### ISSUE TITLE
any way to use less processor CPU?

### ISSUE THREAD

**Issue by blockops1** [ZencashOfficial/zencash-swing-wallet-ui#3] opened 2017-07-29 21:53 UTC
When I run swing wallet on linux zend is using 100% of a processor. Is there any way to reduce the amount of CPU used by Swing wallet? Maybe have it update less often? Perhaps this can be configurable?

**Comment by vaklinov** [comment] 2017-08-01 05:39
It is normal/expected for zend to be using 100% CPU (or more) when it is synchronizing the blockchain or there is a JoinSplit going on. However when zend is synchronized and is idle with only requests from the GUI wallet coming, the typical CPU percentage taken is:

GUI wallet: 0-20% 
zend: 0-10%

If you have observed significant CPU consumption on an idle wallet, this may be an issue - needs to be reproduced so it may be diagnosed...

There is a known limitation on Linux that might confuse users as to the exact CPU% taken at one time, listed among the known limitations: The CPU percentage shown to be taken by zcashd on Linux is the average for the entire lifetime of the process. This is not very useful. This will be improved in future versions. The reason for this is that the Linux command used to get the CPU % is `ps auxwwww` etc.

Not withstanding the above, I agree it would be useful to allow the GUI wallet to be configurable with respect to the update interval for the balance/transactions etc. uch intervals may be configured in some "Wallet >> Options >> Advanced" section of the GUI - to be created as an enhancement.

**Comment by St3x** [comment] 2019-02-09 13:52
Can this issue be closed ?

**Comment by Sto1cNate** [comment] 2019-04-25 22:17
@zennermac should be able to close this one.

**Closed** 2019-04-25 23:04 UTC
Labels: enhancement
