### ISSUE TITLE
ZEN Cash Wallet error

### ISSUE THREAD

**Issue by eMining** [ZencashOfficial/zencash-swing-wallet-ui#64] opened 2018-02-03 13:14 UTC
A general unexpected critical error has occurred:
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

Hi all,

I am receiving the following error each time I started the wallet. I would remove the whole wallet from the system and install it again if I have private keys. But I don't have private keys. Could someone help me to fix this problem or how I can get my private keys?

Thanks.

**Comment by vaklinov** [comment] 2018-02-03 17:42
This appears to be the known problem of a broken/corrupt block-chain. In most cases it can be fixed safely.  Some manual repairs will be necessary.

The ZEN private keys are located in the wallet.dat file in directory %APPDATA%/Zen/. To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running.

Once you make sure you have a wallet backup in a safe place, this problem is most commonly solved by re-indexing the block-chain. For details of how to reindex, see the troubleshooting guide: https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

**Comment by LordMajestros** [comment] 2018-02-10 11:28
What does reindexing do? Does it simps reindex the local copy or does it redownlaod the whole block chain?

**Comment by vaklinov** [comment] 2018-02-11 16:43
Reindexing does not re-download the blockchain data from the network. It only recreates the blockchain database and rechecks the data in it.

**Comment by bobwilson100** [comment] 2018-02-11 21:14
I am having the same issue.  2 items worth noting.  I am on a Mac.
1) When I go to Library/Application Support/ , I do not have a Zen folder for some reason.
2) I read the instructions to reindex and kicked that off.  You didn't mention if we needed to wait until reindexing is complete before trying again.  I assume so, but I only see that I am "validating transactions" when I run the command to reindex.  Not sure how I know when it is done.

Thanks in advance!

**Comment by vaklinov** [comment] 2018-02-12 20:48
The issue with the wallet not starting properly is due to a broken local block-chain. The underlying technical cause is not in the GUI itself but in the ZEN core/node. The problem is being investigated as a priority by the ZEN core team. It started occurring recently with high frequency without any software changes - it is related to network load/transactions/block content. Once a fix is made available a new wallet release will be made. The workaround to do reindexing is not very convenient but still allows uses to recover from the problem. 

As to the questions/issues:
o You can open the GUI wallet while re-indexing is taking place. However until reindexing ends and you have a 100% synchronized blockchain, the UI will show an old state of the wallet, old balance etc.
o There are several different folders of type Library/Application Support/ on a Mac. You need the one inside your user account  /Users/<username>/Library/Application Support/
o You can consider reindexing as complete when your blockchain synchronization indicator (lower right UI corner) shows 100%. 

Users who encounter the problem more than once may also store a “good” copy of the blockchain for later re-use as mentioned in this post: https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/

**Comment by CryptoMang** [comment] 2018-02-14 04:29
Mine doesn't show my old balance..shows no balance.

**Comment by LordMajestros** [comment] 2018-02-14 06:04
Have your addresses changed?
You can check https://explorer.zen-solutions.io using your addresses to see if your funds are still in your address. Then import  your private keys if you still have them.

**Comment by CryptoMang** [comment] 2018-02-14 13:41
No, my address hasn't changed.  So I was reindexing and it wasn't showing any balances.  Then after the reindex my balances showed correctly.  I closed the wallet then reopened it and I'm back to my original "EOF" error.

**Comment by zenmonies** [comment] 2018-02-14 14:07
I am having this same error on start up. When I run the zend -reindex command it says 'zend' is not recognized as an internal or external command, operable program or batch file. The directions say "On Windows you first have to locate zend.exe. It is in the /app sub-directory of the wallet installation." I have located that but what exactly do you do once you locate it?

Thanks

**Comment by CryptoMang** [comment] 2018-02-14 14:18
You need to make sure you're in the "zen" directory.  I made the same mistake yesterday. %appdata%\zen

**Comment by zenmonies** [comment] 2018-02-14 14:26
Thank you. So I just need to go to that directory then run the command? Because I did that and still get the same message. :(

**Comment by CryptoMang** [comment] 2018-02-14 14:29
I'm sorry...I have you bad info...you need to go to the "app" folder...where your wallet.exe is located and run zend -reindex from there.

**Comment by zenmonies** [comment] 2018-02-14 14:38
Dang. That doesn't work either. Well... I have backups and the private keys so hopefully when I get the chance to reinstall a fresh wallet I can restore it that way.

**Comment by CryptoMang** [comment] 2018-02-14 14:39
what directory did you go to?

**Comment by CryptoMang** [comment] 2018-02-14 14:43
here's my path; C:\Users\wegen\Downloads\ZENCashDesktopGUIWallet_0.75.8\app

Inside the "app" directory is where your zend.exe should be.

**Comment by zenmonies** [comment] 2018-02-14 14:51
here is mine. Maybe I'm in the wrong spot? But the zend.exe is there
C:\Users\Calvin\Documents\Vault\Zen\app

**Comment by vaklinov** [comment] 2018-02-14 18:37
@zenmonies You need to open a Windows command prompt and change the current directory to where zend.exe is located, like:
```
cd C:\Users\Calvin\Documents\Vault\Zen\app
```
To make sure zend.exe is located there use the `dir` comamnd - it should list it. After that the command
```
zend -reindex
```
should work.

**Comment by zenmonies** [comment] 2018-02-14 18:45
@vaklinov I think I am getting somewhere now. It is running through the validation process. Thank you!

**Comment by dcryptob** [comment] 2018-02-14 21:35
@vaklinov having same issue and I am not computer savvy. this is the location of my zend.exe file:
C:\Users\Demetrius\Desktop\zencash\app
not sure what you mean by making sure zend.exe is there by air command and adding the zend -reindex

in terminal:
C:\Users\Demetrius>zend - reindex
'zend' is not recognized as an internal or external command,
operable program or batch file.

Complete noob on my end i did not get private keys before having the issue and do not know what program to use to open my wallet.bat file
need help plz from anyone if @vaklinov isnt available. trying to move funds from swing wallet to Arizen

**Comment by dcryptob** [comment] 2018-02-14 21:39
@vaklinov not sure if this helps but its from the bug.log 

018-02-08 07:54:39 UpdateTip: new best=0000000012ffa5948790ce3b97a0b1200a879b8d57e9a783f0a124a50808bd99  height=253545  log2_work=48.576868  tx=1277526  date=2018-02-07 23:23:54 progress=0.999475  cache=50.4MiB(16465tx)
2018-02-08 07:54:39 tor: Thread interrupt
2018-02-08 07:54:39 torcontrol thread exit
2018-02-08 07:54:39 scheduler thread interrupt
2018-02-08 07:54:39 addcon thread interrupt
2018-02-08 07:54:39 opencon thread interrupt
2018-02-08 07:54:39 poolscleaner thread interrupt
2018-02-08 07:54:39 net thread interrupt
2018-02-08 07:54:39 UpdateTip: new best=0000000024bbe554e01f5adbb6c8b3b33dc288c3c9c06617ddbbc5d6808f68d3  height=253546  log2_work=48.576894  tx=1277555  date=2018-02-07 23:26:41 progress=0.999478  cache=50.7MiB(16514tx)
2018-02-08 07:54:39 msghand thread interrupt
2018-02-08 07:54:39 Shutdown: In progress...
2018-02-08 07:54:39 StopRPC: waiting for async rpc workers to stop
2018-02-08 07:54:39 StopNode()
2018-02-08 07:54:40 Shutdown: done
2018-02-14 17:54:17

**Comment by dcryptob** [comment] 2018-02-14 21:53
@vaklinov more info from bug.log


[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] Starting ZENCash Swing Wallet ... 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] OS: Windows 10 = WINDOWS 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] Current directory: C:\Users\Demetrius\Downloads\ZENCashDesktopGUIWallet_0.75.8\app 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] Class path: C:\Users\Demetrius\Downloads\ZENCashDesktopGUIWallet_0.75.8\app\ZENCashSwingWalletUI.jar;bitcoinj-core-0.14.5.jar;sqlite-jdbc-3.21.0.jar 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] Environment PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\Demetrius\AppData\Local\Microsoft\WindowsApps; 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] Using ZENCash utilities: zend: C:\Users\Demetrius\Downloads\ZENCashDesktopGUIWallet_0.75.8\app\zend.exe, zen-cli: C:\Users\Demetrius\Downloads\ZENCashDesktopGUIWallet_0.75.8\app\zen-cli.exe 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] zend is not runing at the moment or has not started/synchronized 100% - showing splash... 
[main] [Wed Feb 14 13:16:53 PST 2018] [INFO] Splash: checking if zend is already running... 
[main] [Wed Feb 14 13:16:54 PST 2018] [INFO] Splash: zend will be started... 
[main] [Wed Feb 14 13:17:09 PST 2018] [ERROR] Unexpected error:  
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:599)

**Comment by zenmonies** [comment] 2018-02-15 13:18
@dcryptob 

Here is what you need to do based on vaklinov's instructions. (Worked for me)

open run command and type (for you): 

cd C:\Users\Demetrius\Desktop\zencash\app

hit enter, then type: 

dir

hit enter, then type:

zend -reindex

hit enter and it should start the process. Takes several hours. Once completed my wallet opened right up.

**Comment by dcryptob** [comment] 2018-02-15 17:30
@zenmonies THX!! work perfectly. I wasn't aware about hitting enter then typing zend -reindex. once again thx for help

**Comment by vaklinov** [comment] 2018-02-15 22:02
The following step-by-step guide for Windows users (created by a third party) is handy: https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/ to help with reindexing in case of encountering the common block-chain problem.

**Comment by i8avet** [comment] 2018-02-19 04:33
is there any info how to use with imac not having to keep terminal open? I have to leave terminal open for Wallet to open correctly. Allowed all day for my wallet to sync 100%. kept on for 5 minutes after. closed wallet and terminal, tried to reopen wallet and same error "code -1". reopened terminal and opened wallet. Blockchain started from 0% again...

**Comment by vaklinov** [comment] 2018-02-19 20:08
@i8avet If you are experiencing the "broken blockchain" too often and you cannot keep the terminal open, unfortunately only other option is maybe to use a different wallet like Arizen that does not have the problem:
https://github.com/ZencashOfficial/arizen

The underlying technical cause is not in the GUI itself but in the ZEN core/node. The problem is being investigated as a priority by the ZEN core team. It started occurring recently with high frequency without any software changes - it is related to network load/transactions/block content. Once a fix is made available a new wallet release will be made. The workaround to do reindexing is not very convenient but still allows uses to recover from the problem.

**Comment by i8avet** [comment] 2018-02-19 20:37
Thank you!

**Comment by vaklinov** [comment] 2018-02-21 23:19
A new release of the ZEN core node has been made that contains a stability fix for the “broken blockchain” problems that many users have experienced recently, that cause the GUI wallet to fail on startup:
https://github.com/ZencashOfficial/zen/releases/tag/v2.0.11

This new ZEN core version will be used in the next GUI wallet releases to fix the problem. Users who do not wish to wait for a new GUI wallet release may use the new ZEN core/node binaries by replacing them in the GUI wallet installation manually. Some details on how to do this: the ZENCash Desktop GUI Wallet includes a full ZEN node and the UI is in effect an interface to the locally running ZEN node. The ZEN node binaries are located in:

Mac OS (absolute file paths):
/Applications/ZENCashWallet.app/Contents/Java/zend
/Applications/ZENCashWallet.app/Contents/Java/zen-cli

Windows: having as a base directory the place where the GUI wallet was unzipped from ZENCashDesktopGUIWallet_0.75.8.zip the binaries are:
/app/zend.exe
/app/zen-cli.exe

If a user has experienced the “broken blockchain” problem more than once before he may replace the ZEN binaries with the ones from the latest release to gain better stability.

Note: If the ZEN blockchain is currently in a broken state, even with the new/fixed binaries users may have to do one final reixdexing operation to avoid the problems. For details on how to reindex the following articles may be consulted:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md
https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/

**Comment by Mer1** [comment] 2018-03-02 09:13
Hello,
I did exactly what you guys said about reindexing, being a complete noob i followed it step by step, but after giving the zend -reindex command, the cmd is telling me:

"error: cannot find the zcash network parameters in the following directory: C:\....\roaming\ZcashParams.
Please run "zen-fetch-params" or "./zcutil/fetch-params.sh" and then restart."

When running eather of those commands it tell me they're not recognized as internal or external command, executable file or batch file.
Any ideas? It's probably a tiny thing i have no idea about because, well, i'm a noob.
Thanks!

**Comment by LordMajestros** [comment] 2018-03-02 09:20
What OS are you on? Windows?

**Comment by LordMajestros** [comment] 2018-03-02 09:24
See here https://github.com/aicjofs/zencash-swing-wallet-ui/blob/master/docs/Readme-Windows.md:
```
1.3. Download the ZenCash Proving Key and store it in directory %APPDATA%\ZcashParams.

1.4. Download the ZenCash Verifying Key and store it in directory %APPDATA%\ZcashParams.
```

**Comment by Mer1** [comment] 2018-03-02 09:26
I already have both those files, in that directory. Are you saying i should replace them?

**Comment by LordMajestros** [comment] 2018-03-02 09:27
Copy them to C:....\roaming\ZcashParams

**Comment by LordMajestros** [comment] 2018-03-02 09:27
Then restart zencash

**Comment by Mer1** [comment] 2018-03-02 09:41
They're there. I have proving key and verifying key inside the roaming\zcashparams folder.
I redowndloaded them, replaced them. Tried opening the wallet, still same error as the start of this post. Tried running zend -reindex again, same error as i stated before.
@vaklinov please rescue me!

**Comment by LordMajestros** [comment] 2018-03-02 09:48
```
Please run "zen-fetch-params" or "./zcutil/fetch-params.sh" 
```
The above will not work on windows. It is a linux bash script file and will only work on linux/os x

What is the full path for C:....\roaming\ZcashParams

**Comment by Mer1** [comment] 2018-03-02 09:53
Oh. Well, fudge.

C:\Users\Perry\AppData\Roaming\ZcashParams , any help?

**Comment by LordMajestros** [comment] 2018-03-02 09:58
Windows isn't case sensitive right?
I can't see any problems with it.
Try `start zend.bat` instead of manually downloading them.

**Comment by LordMajestros** [comment] 2018-03-02 10:02
Check that you have permissions for that directory.
Start zen as an admin and see if that works.

**Comment by Mer1** [comment] 2018-03-02 10:05
Says zend.bat is impossible to find, which dir should it be in?

Thank you so much for your time, btw!

**Comment by LordMajestros** [comment] 2018-03-02 10:37
It's not in the release anymore. (If it was before).
Here's what I think. Create a new user account and copy the blockchain folder and proving keys there and try it again. If you have another computer try it there. It might be some obscure setting on your user/machine.
Also try to remember if you made any system wide changes recently.

**Comment by Mer1** [comment] 2018-03-02 11:33
Ok, I'm doing that on another pc. Thank you! I'll update when I'm done.

**Comment by bahnstoermer** [comment] 2018-04-09 18:24
I also ran into code -1, and it was because sync'ing the block chain took so long I had to risk closing the wallet to move the machine; sadly I paid the price I hoped I wouldn't (code -1) which appears to be mean corrupted block chain file (and that explanation matches the actions I took).  The app couldn't handle a close while sync'ing apparently. 

So I'm on OSX for crypto (but not a Mac power user let's say) and looked for  /Users/[username]/Library/Application Support/ and that directory isn't present.  

I have a file in a folder that I set up as my backup directory, and it's 106kb of file that OSX nor Windows (when put on a USB drive and transferred, just to look at) will show me an extension for (ugh, I'm feeling stupid now).  OSX says unix executable, opening with a text editor show binary gibberish.  So I'm not sure if this is my file or not, a search for wallet.dat across the whole machine doesn't pull anything.  

I have my private key and public address, but don't want to take any action without more guidance... input from the group?  Thank you for any thoughts...

**Comment by vaklinov** [comment] 2018-04-09 19:45
@bahnstoermer Merely stopping the GUI wallet while the block-chain is being synchronized should not result in a broken local block-chain (tried many times). However we cannot rule out this kind of problem happening in some/rare cases :-|

If you are not an experienced Mac user as a start it may be advisable to get familiar with using the Mac terminal: https://www.macworld.co.uk/how-to/mac-software/how-use-terminal-on-mac-3608274/

I am sure the directory  /Users/[username]/Library/Application Support/Zen exists. On a terminal you may list it with a command like:
```
$ ls -lh ~/Library/Application\ Support/Zen/
total 98680
drwx------   51 user  staff   1,7K 16 Мар 22:53 blocks
-rw-------    1 user  staff   920B 19 Сеп  2017 cert.pem
drwx------  170 user  staff   5,6K 17 Мар 20:45 chainstate
-rw-------    1 user  staff     0B 16 Юли  2017 db.log
-rw-------    1 user  staff   6,3M 17 Мар 22:58 debug.log
-rw-------    1 user  staff    33K 17 Мар 22:58 fee_estimates.dat
-rw-------    1 user  staff   1,7K 19 Сеп  2017 key.pem
-rw-------    1 user  staff   3,2M 17 Мар 22:58 peers.dat
-rw-------    1 user  staff    10M 17 Мар 22:58 wallet.dat
-rw-r--r--    1 user  staff   723B 18 Юли  2017 zen.conf
```

Once you establish that the directory is there, you may follow the directions to backup the `wallt.dat` and re-index the blockhcain...

**Comment by bahnstoermer** [comment] 2018-04-09 19:50
Thank you for the response.  I found my wallet.dat file and have backed it up off line.  I read that OSX High Sierra may have been part of the problem.  

Regardless, I'm scanning the above posts for OSX re-indexing instructions now.

**Comment by bahnstoermer** [comment] 2018-04-10 17:54
![image](https://user-images.githubusercontent.com/38225230/38574282-4ea6204e-3cad-11e8-9851-4564448a99bf.png)

Ok the validations have slowed to 1 every couple seconds... does that mean I'm "caught up?"  How do I know when it's safe to stop the process and re-launch the GUI wallet?

Thanks in advance...

**Comment by zenportodev** [comment] 2018-04-10 18:43
It is not necessary to stop zend's reindexing before launching the GUI wallet. If you start the GUI it will use the zend already started... and if the GUI shows 100% blockchain synchronization, then reindexing has finished.

**Comment by bahnstoermer** [comment] 2018-04-10 18:57
![image](https://user-images.githubusercontent.com/38225230/38577613-45bd8482-3cb6-11e8-8713-e892f3ed45d5.png)

Thanks for helping me get this straightened out!

**Comment by roguecryptovestor** [comment] 2018-04-22 19:51
I am having the same error. I am a noob using a Mac and was able to get to terminal but when I enter /Applications/ZENCashWallet.app/Contents/Java/zend -reindex on the terminal command line. I get an error " -bash:/ Applications/ZENCashWallet.app/Contents/Java/zend: No such file or directory" can some tell me how I go about executing the reindexing of zend on terminal command line.

I also tried  typing  zend -reindex while in the Zen directory and I command not found. I have attached below. Any help is appreciated.

![2018-04-22_12-44-051](https://user-images.githubusercontent.com/38633770/39099203-5e4c4852-462b-11e8-930d-5ff25c14371b.jpg)

**Comment by roguecryptovestor** [comment] 2018-04-22 23:26
LordMajestros thank you for feedback. I tried typing the above per you suggestion and I get the following message "No such file or directory. I am wondering if I am I even in the correct directory to be running zend -reindex command?  The only zend file I see is zend.pid not a zend.exe file. I tried following github docs as best as I can. As far as java suggestion unfortunately I am not a savvy programmer so I would not even know where to start.

Here is screenshot of my terminal inputs and the directory I am trying to perform reindex:

![2018-04-22_16-16-19a](https://user-images.githubusercontent.com/38633770/39101076-5d0247c6-4649-11e8-9031-941b7c7d6c7c.jpg)

**Comment by LordMajestros** [comment] 2018-04-23 00:28
Ok, the issue is you don't have the zen binary in that folder.
You can get it here https://github.com/ZencashOfficial/zen/releases/tag/v2.0.11
The file to get is  Zen_Mac_binaries_v2.0.11.zip and check the signature matches  Zen_Mac_binaries_v2.0.11.zip.asc
Or you can try what I suggested earlier. If you have the swing wallet then go to Applications select open in finder.
Right click ZENCashwallet.App select "Show Package Contents" 
Open the "Contents" folder
Open the "Java" 
Copy out "zend" and "libs"
Paste in a folder somewhere else maybe your desktop. 
Let's call the folder zencash.
open a terminal and type "cd /Users/prousermac/Desktop/zen"
then this ./zend -datadir="/Users//Library/Application Support/Zen" -reindex

**Comment by LordMajestros** [comment] 2018-04-23 00:29
Let me know any issues you encounter

**Comment by roguecryptovestor** [comment] 2018-04-23 04:36
Thank you LordMajestros. I went with option 2 and it seems to be synchronizing now. On Friday before it failed Blockchain synchronized was 98%. it looks like reindexing starts the synchronization from scratch back to 0%. I will let you know if I have any other issues.  Do you think it is still necessary to download zen binary or can I use option 2 for reindexing if I run into issue again. I really appreciate all your help.

**Comment by LordMajestros** [comment] 2018-04-23 10:10
You can use option 2, there is no need to download the zen binary again unless there is an update.
Yes, reindexing starts from 0% but it doesn't download anything till it's done with the blockchain on your disk then it continues as normal updating the blockchain as new blocks are found.
You're welcome 😀

**Comment by roguecryptovestor** [comment] 2018-04-23 17:25
LordMajestros the swing wallet stop synchronizing an got the following error after getting to 98% again. Can you please advise me on what to do. Should I download latest Swing wallet (current version is ZENCash Desktop GUI Wallet 0.75.9) and try to reindex  through terminal again or should I do something else. I am afraid to do anything at this point in fear of losing my zencash. Ultimately I would like to move my zencash after full synchronization to Arizen or Ledger Nano S so I do not have to keep updating the blockchain. Is there a way to do this without the synchronizing. I really appreciate your help.

Here is the following error on Terminal window:
![2018-04-23_10-10-05a](https://user-images.githubusercontent.com/38633770/39142636-12097b76-46e0-11e8-96da-bdd2e1c62751.jpg)

Here is error on swing wallet menu:
![2018-04-23_10-08-54a](https://user-images.githubusercontent.com/38633770/39142718-47104b10-46e0-11e8-802e-4b6a29aca37f.jpg)

**Comment by LordMajestros** [comment] 2018-04-23 18:26
The blockchain is stored in ~/Library/Application Support/Zen/ (OSX) and %APPDATA%/Zen/ on windows. the swing wallet is in your Applications folder on OSX and in Program Files on Windows
So no downloading it shouldn't cause a problem. @roguecryptovestor 
You can get the latest release here: https://github.com/ZencashOfficial/zen/releases/tag/v2.0.11 for the command line tool and here https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases/download/0.81.0/ZENCashWallet-0.81.0.dmg for the GUI Version which contains the latest zend version

**Comment by anderson-sean** [comment] 2018-04-24 00:33
I tried the first stage, which is of reindex the block-chain with this guide " https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md". But I cannot even launch  "Zend.exe". The "zend.exe" app dashes during 1sec then it stops working. I use win8

**Comment by zenportodev** [comment] 2018-04-24 05:15
@anderson-sean zend writes a log on Mac OS at:
~/Library/Application Support/Zen/debug.log
If zend cannot start, there is probably an error message in that log that shows why...

**Comment by Aphiso** [comment] 2018-05-29 14:56
Backup the wallet.dat.

I had this error on linux due to my zen.conf file being incorrectly setup. That file is located in your userdirectory/.zen/zen.conf and a very basic conf file should look like this:
```
rpcuser=username
rpcpassword=Random Password Goes Here

addnode=23.227.163.203
addnode=198.27.98.171
addnode=50.116.39.40
addnode=23.92.31.218
addnode=45.79.64.189
addnode=23.227.163.200
addnode=144.76.92.119
addnode=163.172.172.171```
```

The addnode's are just secure nodes I added. You do not need to specify an RPC port and your zen.conf may be doing so. Note: The username doesnt need to be changed. Leave it as username. Only change the password and just use a password generator to be safe. You won't need it for anything in the wallet itself.

**Comment by Andy515** [comment] 2018-07-13 16:23
Hi.
When I tape %appdata%\Zen I don’t see wallet.dat
These all what are available :
blocks
chainstate
database
.lock
cert.pem
db
debug
free_esimates
key.pem
peers
wallet
zen.conf

How can I back up my wallet? I’m om windows 7

Thanks in advance

**Comment by zenportodev** [comment] 2018-07-13 20:11
This document describes the backup in more detail, with screen-shots:
https://zencash.atlassian.net/wiki/spaces/ZEN/pages/7176693/ZENCashWallet+Swing+Wallet+-+Backup+and+Upgrade

**Comment by Andy515** [comment] 2018-07-16 16:49
Thanks tarrenj

I went through reindexing process, it takes almost 3 days. 
But now in CD command there is following  message :
![zen disable deprecation](https://user-images.githubusercontent.com/41202736/42771875-76647cce-8920-11e8-8708-74533d56b7d4.png)

**Comment by tarrenj** [comment] 2018-07-16 16:53
Ahh, that's a quick one, you just need to update your swing wallet to the most recent version.

**Comment by Andy515** [comment] 2018-07-16 16:54
And I still can't open my Zen wallet.
Any idea haw can I upgrade to the latest version ?

**Comment by tarrenj** [comment] 2018-07-16 17:48
@Andy515, this link should help you: https://zencash.atlassian.net/wiki/spaces/ZEN/pages/7176693/ZENCashWallet+Swing+Wallet+-+Backup+and+Upgrade

**Comment by St3x** [comment] 2019-02-09 14:06
This is how I recovered my wallet on Windows 10 :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by Sto1cNate** [comment] 2019-04-25 22:53
@zennermac should be able to close this one.

**Closed** 2019-05-01 13:51 UTC
Labels: support case
