### ISSUE TITLE
Be able to copy the memo of a message to the clipboard

### ISSUE THREAD

**Issue by blockops1** [ZencashOfficial/zencash-swing-wallet-ui#4] opened 2017-07-31 15:20 UTC
I am using it to send addresses and urls. I need to be able to copy those. Also, long message go far across the screen. The view screen for memo should wrap at about 60 characters or so

**Comment by vaklinov** [comment] 2017-08-01 05:28
Accepted as an enhancement: the memo to be visualized in a better dialog box, in a text area with approx 60 characters per line. An additional button should allow the memo to be copied to clipboard.

**Comment by vaklinov** [comment] 2017-08-30 19:14
The issue is now partly fixed in the Git master branch:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/tree/master
The transaction memo is copied to the clipboard.

**Comment by vaklinov** [comment] 2017-10-03 10:18
The memo is now shown wrapped on the screen (in the latest commit), so long memos do not create extremely wide UI message boxes. The matter of "an additional button" is not yet implemented. The memo is always automatically copied to the clipboard. This issue will be closed at a later time when a new UI dialog is created to have an additional button...

**Comment by Sto1cNate** [comment] 2019-04-25 22:18
@zennermac should be able to close this one.

**Closed** 2019-04-25 23:04 UTC
Labels: usability issue
