### ISSUE TITLE
Unable to access wallet after upgrading while EOF reached (code 1)

### ISSUE THREAD

**Issue by mex20** [ZencashOfficial/zencash-swing-wallet-ui#116] opened 2018-07-16 04:11 UTC
The swing wallet has been upgraded to the newest wallet version from previous version while having the typical "EOF reached (code 1)" problem, and now the following error happens. The wallet is unaccessible because of this error. If tried with a brand new 0 balance wallet.dat file, the swing wallet opens right away and functions as expected. The directory that is referenced in the error message is non-existent on the system. Also the blacked out portion is a wallet address, and nothing that is referenced in the error message is true. The wallet has never been turned to testnet from mainnet. 
![walletissue](https://user-images.githubusercontent.com/12109514/42607509-e985656e-8548-11e8-91a6-829b219bca3f.JPG)

**Comment by zenportodev** [comment] 2018-07-17 04:47
The error message indicates that the messaging identity address is not found in the wallet.dat. This address is stored in the …\messaging directory together with the local messaging history. There could be different reasons for this but the most likely explanation is: “tried with a brand new 0 balance wallet.dat file”. The new wallet.dat does not have the address…

The messaging directory %LOCALAPPDATA%/ZENCashSwingWalletUI/messaging
must exist. If it cannot be found simply by using the file explorer title bar, you may search for a directory named  ZENCashSwingWalletUI…

The most important part of upgrading is to make a good local copy of the original wallet.dat file. - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every few outgoing transactions) and it MUST also be backed up after creating a new Z address.

A document describing backup and upgrade is:
https://zencash.atlassian.net/wiki/spaces/ZEN/pages/7176693/ZENCashWallet+Swing+Wallet+-+Backup+and+Upgrade

**Comment by zenportodev** [comment] 2018-07-17 18:24
With the more detailed description provided, the problem is clearer: the root cause and the real issue is that: "The original wallet.dat is unable to be loaded in the GUI wallet." - actually the GUI does not access the wallet.dat - only the ZEN core (zend.exe) reads and writes it. The error message about messaging identity address is just a consequence (address is not found in the new/0 balance wallet.dat ).

So about the real problem: if upon start zend cannot load the wallet.dat and renames the original wallet.dat to a .Bak file - this is bad. It could be due to file content corruption. The Zend log probably has more information. It is located at Windows dir.  %APPDATA%/Zen/debug.log

If the problem persists it may be a good idea to request support - https://support.zencash.com/
One thing to try may be to restore the wallet.dat from a recent backup - if the backup is up to date, the balance will be fully restored... The wallet.dat needs to be backed up regularly (not just once - say after every few outgoing transactions) and it MUST also be backed up after creating a new Z address.

**Comment by mex20** [comment] 2018-07-19 03:41
Alright, after pouring through the logs, the most prevalent thing is this:
2018-07-16 00:15:56 ERROR: AcceptToMemoryPool: joinsplit requirements not met
2018-07-16 00:16:14 ERROR: AcceptToMemoryPool: joinsplit requirements not met
2018-07-16 00:16:43 ERROR: AcceptToMemoryPool: joinsplit requirements not met
2018-07-16 00:16:45 ERROR: AcceptToMemoryPool: joinsplit requirements not met
2018-07-16 00:16:46 ERROR: AcceptToMemoryPool: inputs already spent

There are some other interesting things in there, but they are more for support, since they contain IP addresses and what I believe to be hashes.

**Comment by St3x** [comment] 2019-02-09 13:16
This is how I recovered my wallet on Windows 10 :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by Sto1cNate** [comment] 2019-04-25 23:15
@zennermac should be able to close this one.

**Closed** 2019-05-01 13:30 UTC
Labels: support case
