### ISSUE TITLE
Zencash Wallet Issue - Cannot Access Wallet Anymore - Error 1 on Mac OS

### ISSUE THREAD

**Issue by ctsounds713** [ZencashOfficial/zencash-swing-wallet-ui#87] opened 2018-04-11 22:37 UTC
Out of no where I started getting the below error on my Mac. 

A general unexpected critical error has occurred:
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

Thankfully, last week I transferred out 90% of my Zen from this wallet but I still have 100 Zen in this wallet that I would really like to get back. 

With the above being said I have done a lot of research on this and see that many people are having a similar issue. 

When I go to /Library/Application Support/ I am unable to find Zen. I cannot locate the wallet.dat file and I cannot locate the zend.exe to reindex the blockchain. 

I really hope someone can help me get this issue resolved. I am more than willing to send some Zen to whoever can help me get this issue resolved. 

Thanks in advance.

**Comment by zenportodev** [comment] 2018-04-12 03:39
This appears to be the known problem of a broken/corrupt block-chain.

The ZEN private keys are located in the wallet.dat file in directory:
Windows: %APPDATA%/Zen/
Mac OS: ~/Library/Application Support/Zen/
To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every 30-40 outgoing transactions) and it MUST also be backed up after creating a new Z address.

Once you make sure you have a wallet backup in a safe place, this problem is most commonly solved by re-indexing the block-chain. For details of how to reindex, one may see the troubleshooting guide: https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

The Zen directory is not in `/Library/Application Support/` (below root) but in `~/Library/Application Support/Zen/` that translates to `/Users/[username]/Library/Application Support/Zen/`...

**Comment by ctsounds713** [comment] 2018-04-12 03:45
It seems like the above is your copy and paste response for this issue. I have seen this exact reply on many people with the same issues posts. Trust me I tried the above before even posting. I don't want to be rude but did you even read my issue? 

I have checked /Users/[username]/Library/Application Support/ and there is no Zen in that folder. 

If this is a known issue then why do you continue to promote a wallet that has issues? It seems like I am now out 100 Zen do to your poor wallet. I am a huge Zen supporter but after this I am not feeling to good about Zen.

**Comment by zenportodev** [comment] 2018-04-12 15:57
Apologies. I do not wish to be rude or offensive either. Did you double check the existence of the directory  `/Users/[username]/Library/Application Support/Zen` via Mac terminal e.g. a command like:

```
$ ls -lh ~/Library/Application\ Support/Zen/wallet.dat 

-rw-------  1 user  staff    10M 17 Мар 22:58 /Users/user/Library/Application Support/Zen/wallet.dat
```
The issue of the GUI wallet not being able to start is usually caused by problems with the local blockchain that prevent `zend` from starting properly, so the GUI cannot start either. When it happens the problem gets fixed via re-indexing. This problem is known across all Z-currencies and it may happen if you run a full node (as the GUI wallet does).

However if the directory `/Users/[username]/Library/Application Support/Zen` has somehow disappeared then this is a wholly-different and not previously known issue...

Again, I do not wish to be offensive, the following command finds all wallets on a system:
```
$ find /Users -name wallet.dat

/Users/user/Library/Application Support/Bitcoin/wallet.dat
/Users/user/Library/Application Support/Zcash/wallet.dat
/Users/user/Library/Application Support/Zen/wallet.dat
```

**Comment by ctsounds713** [comment] 2018-04-14 20:01
So I was able to reindex the wallet. 24 hours later when the wallet hit 99.5% completed the reindex failed. Thankfully, I was able to get the money off the wallet. As much as I love Zen, I could never recommend this wallet to another person. There is just far to many issues with it. I am not sure why you are still promoting this wallet with all the issues it has. Hopefully, you will come out with a secure hardware wallet in the future. Until then, I will either be selling all the Zen I mine or will avoid Zen entirely. I am a huge supporter of this project so it really disappoints me that you have a wallet with so many bugs. I even have a Zencash Group I started on Facebook with more than 9000 members. Hopefully, they will be fixed soon so I can open up a few Super Nodes and Secure Nodes. I look forward to you improving your service, until then I will be suggesting that everyone avoids this wallet.

**Comment by St3x** [comment] 2019-02-09 13:03
This is how I recovered my wallet on Windows 10 (translate it to MacOS) :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by zennermac** [comment] 2019-04-25 19:07
I am going to close out this issue now as we have not heard anything for quite some time.
What I would say is to go grab Sphere By Horizen from the website if you have not done so already.

The new release was made public very recently.

**Closed by zennermac** 2019-04-25 19:07 UTC
Labels: support case
