### ISSUE TITLE
Wallet Communication Error (Mac)

### ISSUE THREAD

**Issue by lavoy** [ZencashOfficial/zencash-swing-wallet-ui#58] opened 2018-01-03 20:30 UTC
Hello, I installed and launched ZenCashWallet 0.75.9 today. When I quit the app, it hung and so I force quit it. Upon relaunching, it gives me this error: 

`There was a problem communicating with the ZENCash daemon/wallet. ...`

<img width="755" alt="screen shot 2018-01-03 at 2 27 39 pm" src="https://user-images.githubusercontent.com/314876/34538574-83c33918-f092-11e7-9492-51dbed27f746.png">

This is reproducible so maybe I can get you so me logs if you let me know where to find them.

macOS 10.12.6 (Sierra), MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by vaklinov** [comment] 2018-01-03 21:44
The hanging upon quitting the App could have been due to `zend` refusing to quit normally. Then after the restart maybe the blockchian was broken so it does not sart. Could you please try reindexing as described in the troubleshooting guide: https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

If it does not start even after reindexing, it is worth looking at the logs:
```
~/Library/Application Support/ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log
~/Library/Application Support/Zen/debug.log
```

**Comment by lavoy** [comment] 2018-01-03 21:58
The reindex failed: [zenlog.txt](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/files/1601842/zenlog.txt)

Here's the log: [ZENCashGUIWallet_2018_1_debug.log](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/files/1601841/ZENCashGUIWallet_2018_1_debug.log)

**Comment by vaklinov** [comment] 2018-01-04 07:03
The Zcash network parameters in the following directory:
"/Users/lavoy/Library/Application Support/ZcashParams"
are missing. Normally the GUI wallet should download the proving key (900 MB) and the verifying key in it on first start. The two key files are named: sprout-proving.key and sprout-verifying.key.

Could you please check the content of this directory. If for some reason the two key files are not available (strange), they may also be downloaded manually from:
https://zensystem.io/downloads/sprout-proving.key
https://zensystem.io/downloads/sprout-verifying.key
and saved in directory "/Users/lavoy/Library/Application Support/ZcashParams"

**Comment by lavoy** [comment] 2018-01-04 14:39
Alright, so that error started after I force quit the app. Then I reinstalled and it still was erroring for me. So then I went into the `Application Support` dirs and cleared out all the info because I figured something was corrupted and reinstalled and it didn't work. I just recreated the dir and launched the app and it's downloading the keys. So that worked! Maybe the app should just create the dir if it doesn't see it though? Thanks for your help 🙏

**Comment by vaklinov** [comment] 2018-01-06 07:24
Good to know that it works now. The GUI wallet automatically creates the directory `~Library/Application Support/ZcashParams` if it does not exist. Why it was not done in your case is a bit of a mystery...

**Comment by kylejohnmoore** [comment] 2018-01-19 04:17
I have the same issue but I was sending money to my wallet when it closed now I am afraid to delete and re download.  How should I proceed?

**Comment by vaklinov** [comment] 2018-01-19 22:42
@kylejohnmoore Do not delete your directory `/Users/<Username>/Library/Application Support/ZcashParams` unless you are sure there is something wrong with it. 

The most important thing is to keep a backup copy of your wallet.dat file - it must never be lost. It may be copied manually when the GUI wallet/zend are not running. 

To try to get the wallet working again, as a start you may try re-indexing as outlined in the troubleshooting guide:  https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

If the wallet does not start even after reindexing, it is worth looking at the logs:
~/Library/Application Support/ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log
~/Library/Application Support/Zen/debug.log

**Comment by 817ortho** [comment] 2018-02-05 02:38
![screen shot 2018-02-04 at 6 29 03 pm](https://user-images.githubusercontent.com/36143900/35786198-6b4d9e30-09da-11e8-978c-b22afbb7d05c.png)
in terminal, i get this error message when running zend 
Cannot obtain a lock on data directory /home/a**/.zen. Zen is probably already running.

i think i messed up with this coding where i replaced txindex=1 to reindex=1 
cat <<EOF > ~/.zen/zen.conf
rpcuser=zenuserorsomebettername
rpcpassword=replacethiswithagoodpassword
rpcport=18231
rpcallowip=127.0.0.1
server=1
daemon=1
listen=1
txindex=1
logtimestamps=1
### testnet config
#testnet=1
EOF

please help me correct this.  im so frustrated. spend 2 full days trying to setup a node and i'm about to give up :(

**Comment by vaklinov** [comment] 2018-02-05 20:16
@817ortho The directory you specify /home/a**/.zen is a Linux home directory yet you also attach a Mac OS screen-shot. What OS exactly are you running?

The message `Cannot obtain a lock on data directory /home/a**/.zen` could also be due to missing access permissions. If you restart the PC, make sure zend is not running and then upon starting it you get this error, then you need to check access rights/permissions. I am not an expert on node configuration - if your problem is not with the GUI wallet itself but with the ZEN node, it is better to address this with core developers.

**Comment by 817ortho** [comment] 2018-02-05 20:25
Thank you for replying.  I was in the process of setting up a zencash
secure node, and I've run into some problems.  The error message "cannot
obtain a lock on data directory" is what pops up after running zend on
terminal (mac).  the screen shot is the error messages from the log file on
my mac (application support/zen).  I'm running sierra OS on my mac
currently.  If this is a node problem, who are the core developers I need
to talk to (like how do i get in contact with one?).  At this point, I just
want to access my wallet and move them back into an exchange.  I give up on
setting up a node.  Please advise.  Thanks

**Comment by vaklinov** [comment] 2018-02-05 21:33
The core developers are the ones working on https://github.com/ZencashOfficial/zen
Some of them are aayanl cronic etc. You can find them on the ZEN forum or the discord chats...

Leaving aside the latter of node setup, if you just want to use the GUI wallet: To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every 30-40 outgoing transactions) and it MUST also be backed up after creating a new Z address.

Since your ZEN node is in an unknown/buggy state maybe it is better to rename the old directory `~/Library/Application Support/Zen/` (make sure nothing is lost) and start the wallet again. You can they copy your safely backed up `wallet.dat` to the freshly created directory `~/Library/Application Support/Zen/` 

... the above is just an idea. I would not presume to know what is best for you...

**Comment by 817ortho** [comment] 2018-02-05 21:55
Good thing I didnt delete the wallet yesterday. I was thinking of deleting
it and reinstalling a fresh copy. phew.

just to be clear, rename the old directory ~/library/application
support/zen backup (should i copy everything first and put these copied
files in a folder in case something gets lost?), delete the wallet, then
reinstall the wallet.  move the wallet.dat file from ~/library/application
support/zen backup into ~/library/application support/zen

my fear is doing something wrong and losing my tokens.  im scared silly of
this.

and i understand your just giving me an idea to help solve my problem,
which i totally appreciate.  but right now, i just dont know what to do....

**Comment by vaklinov** [comment] 2018-02-06 22:20
I think the above plan is good. As long as you do not delete the directory: `~/Library/Application Support/Zen/` but just rename it, you will be able to restore it if necessary. It is a good idea to keep a backup copy of the wallet.dat also on another drive/medium that can survive any crash of the PC where the wallet currently is...

The part with deleting and reinstalling the GUI wallet Mac App is not necessary, I think.

**Comment by 817ortho** [comment] 2018-02-06 22:33
thanks for clarifying and for helping me through this process. i will try
this once I get home.  fingers crossed everything works

**Comment by 817ortho** [comment] 2018-02-19 06:10
Hi,

So I did what you instructed, and made a backup file of the original zen
folder.  Reopened zen, copied the original wallet.dat to the new zen
folder. it shows transactions going out, but there's a zero balance in my
account.  How do I retrieve my tokens?  Please help! I have this really sad
sinking feeling right now.

**Comment by 817ortho** [comment] 2018-02-19 07:23
and now, there are no addrresss listed in the overview tab.  it says z
address not listed by wallet when before it showed an address.  please
help!

**Comment by vaklinov** [comment] 2018-02-19 20:15
@817ortho Until the block-chain is synchronized 100% the wallet  shows an old/stale balance - so zero balance with a blockchain synchronized to an old date before you got your ZEN is to be expected. The message "z address not listed by wallet" is shown for all outgoing transactions sent to a Z address - so this is not a surprise.

So did you get your expected balance after the blockchain got 100% synchronized?

The ZEN private keys are located in the wallet.dat file in directory:
Windows: %APPDATA%/Zen/
Mac OS: ~/Library/Application Support/Zen/
To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every 30-40 outgoing transactions) and it MUST also be backed up after creating a new Z address.

**Comment by 817ortho** [comment] 2018-02-20 02:27
Thank you for clarifying this.  I came home to see that my blockchain is
100% synced now, and my tokens are there! Phew!!

Now the question is, do I start all over setting up a node...It's been such
an ordeal.  Thanks again for all your help!!

**Comment by vaklinov** [comment] 2018-02-20 18:15
@817ortho If you are deeply affected by the problem with the "broken blockchain" it may be a better idea to wait for an official fix for the ZEN core/node (it will hopefully come this week). The GUI wallet will also be updated after that with the fix. One other option is maybe to use a different wallet like Arizen that does not have the problem: https://github.com/ZencashOfficial/arizen

**Comment by 817ortho** [comment] 2018-04-23 16:55
Hi,

I just downloaded the newest version of the ZEN wallet for mac. however,
I'm getting the error message "zencashwallet" can't be opened because it is
from an unidentified developer.  Your security preferences allow
installation of only apps from the App stores and identified developers.

I tried to install the latest version because it's been a couple months
since I've opened the wallet, and when i tried to sync it to the
blockchain, an error message popped up (unable to connect to blockchain? or
something along those lines).  I'm trying to transfer some of the coins
back to an exchange so I can sell them.  I would appreciate any help you
could offer in resolving this matter.  Thanks!

**Comment by zenportodev** [comment] 2018-04-23 19:02
@817ortho You may need to (at least temporarily) allow the installation of "apps downloaded from anywhere" on your Mac. This article is a good description of how to do this: http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/

**Comment by 817ortho** [comment] 2018-04-24 08:07
Thank you for sending that link.  I was able to change my settings, and get
the new version to load. However, I'm still having a problem trying to
transfer coins to an exchange.  My addresses are not confirmed, and was
wondering how I could confirm an address inside my zen wallet.  Please
advise.  Thanks

**Comment by zenportodev** [comment] 2018-04-24 15:15
@817ortho Addresses are not subject to confirmations. Transactions are subject to confirmations. Before transferring the ZEN out one needs to wait for the blockchain to be 100% synchronized - or else change sent back will remain invisible until synchronized. If after the blockchain to be 100% synchronized there are still unconfirmed transactions, this could be investigated...

**Comment by 817ortho** [comment] 2018-04-25 04:31
My blockchain is 100% synced, but the addresses with a balance are not
confirmed.  please advise. Thank you for all your help

**Comment by zenportodev** [comment] 2018-04-25 05:06
So you see a ZEN balance for an address  but it is not confirmed? Maybe some transactions have been sent with zero fee. Could you look at your transactions UI TAB and see if any transactions are not confirmed...

**Comment by 817ortho** [comment] 2018-04-25 17:34
I may have sent some transactions with a zero fee.  If that's the case, how
do I resolve it?  I apologize for not looking at the transaction UI Tab
before replying back. I will do so when I get home tonight.  Thanks

**Comment by 817ortho** [comment] 2018-04-26 04:45
so..i just checked and now the transactions are confirmed.  I don't get
it.  They weren't confirmed as of last night.  and I was 100% synced to the
blockchain last night.  Is this normal?  As always, I appreciate your help
throughout this entire process.

**Comment by zenportodev** [comment] 2018-04-26 05:24
@817ortho I am not sure why some transactions may have remained unconfirmed. It was probably not a GUI wallet issue (per se). To avoid this one may increase the transactions fee... when making new transactions.

PS: Make sure you backup your wallet.dat regularly etc.

**Comment by 817ortho** [comment] 2018-04-26 05:38
I havent made any transactions since transferring the coins into the
wallet.  That's so odd.

If you don't mind, how do i back up the wallet.dat file? do i just copy the
file from today, and save it in a dif folder?

**Comment by St3x** [comment] 2019-02-09 14:04
Can this resolved issue be closed ?

**Comment by Sto1cNate** [comment] 2019-04-25 22:49
@zennermac should be able to close this one.

**Closed** 2019-05-01 13:51 UTC
Labels: support case
